#pragma once

namespace tls::alerts {
	/* 8 bit unsigned integer */
	enum struct AlertDescription {
		CLOSE_NOTIFY,
		UNEXPECTED_MESSAGE = 10,
		BAD_RECORD_MAC = 20,
		DECRYPTION_FAILED,
		RECORD_OVERFLOW,
		DECOMPRESSION_FAILURE = 30,
		HANDSHAKE_FAILURE = 40,
		NO_CERTIFICATE,
		BAD_CERTIFICATE,
		UNSUPPORTED_CERTIFICATE,
		CERTIFICATE_REVOKED,
		CERTIFICATE_EXPIRED,
		CERTIFICATE_UNKNOWN,
		ILLEGAL_PARAMETER,
		UNKNOWN_CA,
		ACCESS_DENIED,
		DECODE_ERROR,
		DECRYPT_ERROR,
		EXPORT_RESTRICTION = 60,
		PROTOCOL_VERSION = 70,
		INSUFFICIENT_SECURITY,
		INTERNAL_ERROR = 80,
		INAPPROPRIATE_FALLBACK = 86,
		USER_CANCELED = 90,
		NO_RENEGOTIATION = 100,
		MISSING_EXTENSION = 109,
		UNSUPPORTED_EXTENSION,
		CERTIFICATE_UNOBTAINABLE,
		UNRECOGNIZED_NAME,
		BAD_CERTIFICATE_STATUS_RESPONSE,
		BAD_CERTIFICATE_HASH_VALUE,
		UNKNOWN_PSK_IDENTITY,
		CERTIFICATE_REQUIRED,
		NO_APPLICATION_PROTOCOL = 120
	};
}
